import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import TopBanner from "@/components/layout/Banner/TopBanner";
import TopNavbar from "@/components/layout/Navbar/TopNavbar";
import Footer from "@/components/layout/Footer";
import HolyLoader from "holy-loader";
import Providers from "./providers";
import { TrackingProvider } from "@/components/tracking/TrackingProvider";
import CookieBanner from "@/components/ui/CookieBanner";
import MetaPixel from "@/components/tracking/MetaPixel"
import { MetaPageViewTracker } from "@/components/tracking/MetaPageViewTracker";

import StickySmartCart from "@/components/StickySmartCart";
import { ProductPreviewProvider } from "@/components/ProductPreviewContext";
import QuickProductPreviewModal from "@/components/QuickProductPreviewModal";
import AuthModal from "@/components/auth/AuthModal";
import AuthQueryHandler from "@/components/auth/AuthQueryHandler";

export const metadata: Metadata = {
  title: "HEALZYP",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/favericonweb.png",
  },
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={satoshi.className}>
        <HolyLoader color="#868686" />
        <TopBanner />
        <Providers>
          <TrackingProvider>
            <ProductPreviewProvider>
              <TopNavbar />
              {children}
              <StickySmartCart />
              <QuickProductPreviewModal />
              <AuthModal />
              <AuthQueryHandler />
            </ProductPreviewProvider>
          </TrackingProvider>
        </Providers>
        <Footer />
        <CookieBanner />
        <MetaPixel />
        <MetaPageViewTracker />
      </body>
    </html>
  );
}
